#!/usr/bin/env node

/**
 * LeaseNFT Initialization Script
 * 
 * This script automates:
 *   1. Creating/testnet funding a Stellar account
 *   2. Building the LeaseNFT Soroban contract
 *   3. Deploying to testnet
 *   4. Generating TypeScript bindings
 *   5. Updating .env with the contract ID
 * 
 * Usage:
 *   node scripts/initialize.js
 * 
 * Requires:
 *   - stellar CLI installed
 *   - Node.js 18+
 */

import "dotenv/config";
import { mkdirSync, writeFileSync } from "fs";
import { execSync, exec } from "child_process";
import path from "path";
import { fileURLToPath } from "url";
import { promisify } from "util";

const __filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(__filename);
const execAsync = promisify(exec);

// Configuration - customize these or use env vars
const STELLAR_ACCOUNT = process.env.STELLAR_ACCOUNT || "lease-nft-dev";
const STELLAR_NETWORK = process.env.STELLAR_NETWORK || "testnet";
const STELLAR_RPC_URL =
  process.env.STELLAR_RPC_URL || "https://soroban-testnet.stellar.org";
const STELLAR_NETWORK_PASSPHRASE =
  process.env.STELLAR_NETWORK_PASSPHRASE ||
  "Test SDF Network ; September 2015";
const CONTRACT_PATH = path.resolve(dirname, "..", "..", "contract");

var smartContracts = [];

async function createUser() {
  console.log(`\n📋 Creating/funding account: ${STELLAR_ACCOUNT}...`);
  try {
    execSync(
      `stellar keys generate ${STELLAR_ACCOUNT} --network ${STELLAR_NETWORK} --fund 2>/dev/null || true`,
      { stdio: "inherit" }
    );
  } catch {
    // Account might already exist
  }
}

async function buildContract() {
  console.log("\n🔨 Building contract...");
  execSync(
    `stellar contract build --manifest-path "${CONTRACT_PATH}/contracts/contract/Cargo.toml"`,
    { stdio: "inherit", cwd: CONTRACT_PATH }
  );
  console.log("✅ Build complete");
}

async function deployContract() {
  console.log("\n🚀 Deploying contract...");
  const { stdout } = await execAsync(
    `stellar contract deploy \
      --wasm "${CONTRACT_PATH}/target/wasm32v1-none/release/lease_nft.wasm" \
      --source ${STELLAR_ACCOUNT} \
      --network ${STELLAR_NETWORK} \
      --rpc-url ${STELLAR_RPC_URL} \
      --network-passphrase "${STELLAR_NETWORK_PASSPHRASE}"`
  );

  const contractId = stdout.trim();
  smartContracts.push({
    alias: "lease_nft",
    contractId,
  });

  console.log(`✅ Contract deployed: ${contractId}`);
  return contractId;
}

async function generateBindings({ alias, contractId }) {
  console.log(`\n📦 Generating TypeScript bindings for ${alias}...`);

  const outputDir = path.resolve(dirname, "..", "packages", alias);
  mkdirSync(outputDir, { recursive: true });

  try {
    execSync(
      `stellar contract bindings typescript \
        --contract-id ${contractId} \
        --network ${STELLAR_NETWORK} \
        --output-dir ${outputDir} \
        --overwrite`,
      { stdio: "inherit" }
    );
    console.log(`✅ Bindings generated at packages/${alias}`);
  } catch {
    console.warn("⚠️  Bindings generation failed, creating placeholder");
    createPlaceholderBindings(outputDir, alias, contractId);
  }
}

function createPlaceholderBindings(outputDir, alias, contractId) {
  mkdirSync(`${outputDir}/src`, { recursive: true });

  writeFileSync(
    `${outputDir}/src/index.ts`,
    `// LeaseNFT Contract Bindings (placeholder)
// Auto-generated by initialize.js

export const contractId = '${contractId}';
export const networkPassphrase = '${STELLAR_NETWORK_PASSPHRASE}';
export const rpcUrl = '${STELLAR_RPC_URL}';

export class Client {
  contractId: string;
  networkPassphrase: string;
  rpcUrl: string;

  constructor(opts: { contractId?: string; networkPassphrase?: string; rpcUrl?: string } = {}) {
    this.contractId = opts.contractId || contractId;
    this.networkPassphrase = opts.networkPassphrase || networkPassphrase;
    this.rpcUrl = opts.rpcUrl || rpcUrl;
  }

  async init() { return { result: undefined }; }
  async list_nft(params: any) { return { result: undefined }; }
  async lease_nft(params: any) { return { result: undefined }; }
  async end_lease(params: any) { return { result: undefined }; }
  async get_listing(params: any) { return { result: undefined }; }
  async get_lease(params: any) { return { result: undefined }; }
}
`
  );

  writeFileSync(
    `${outputDir}/package.json`,
    JSON.stringify(
      {
        name: alias,
        version: "0.1.0",
        main: "src/index.ts",
        types: "src/index.ts",
      },
      null,
      2
    )
  );
}

function updateEnvFile(contractId) {
  console.log("\n📝 Updating .env file...");
  const envContent = `# Stellar Network Configuration
NEXT_PUBLIC_STELLAR_NETWORK=${STELLAR_NETWORK}
NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE=${STELLAR_NETWORK_PASSPHRASE}
NEXT_PUBLIC_STELLAR_RPC_URL=${STELLAR_RPC_URL}

# Deployed LeaseNFT Contract Address
NEXT_PUBLIC_CONTRACT_ID=${contractId}
`;

  writeFileSync(path.resolve(dirname, "..", ".env"), envContent);
  console.log("✅ .env file updated");
}

async function main() {
  console.log("╔══════════════════════════════════════╗");
  console.log("║     LeaseNFT Deployment Script       ║");
  console.log("╚══════════════════════════════════════╝");
  console.log(`Network: ${STELLAR_NETWORK}`);
  console.log(`Account: ${STELLAR_ACCOUNT}`);

  createUser();
  buildContract();
  const contractId = await deployContract();

  for (const contract of smartContracts) {
    await generateBindings(contract);
  }

  updateEnvFile(contractId);

  console.log("\n🎉 Deployment Complete!");
  console.log(`\nContract ID: ${contractId}`);
  console.log(`Explorer: https://stellar.expert/explorer/testnet/contract/${contractId}`);
  console.log(`\nNext steps:`);
  console.log(`  1. cd client && bun add file:./packages/lease_nft`);
  console.log(`  2. cd client && bun run dev`);
  console.log(`  3. Visit http://localhost:3000 to use the app`);
}

main().catch((e) => {
  console.error("❌ Initialization failed:", e.message);
  process.exit(1);
});
